site_name: APIFlask
site_description: A lightweight Python web API framework.
site_url: https://apiflask.com
docs_dir: docs_zh
theme:
  name: material
  custom_dir: docs_zh/_templates
  logo: _assets/white-logo.png
  favicon: _assets/favicon.png
  palette:
    primary: deep orange
  icon:
    repo: fontawesome/brands/github
  language: zh
repo_url: https://github.com/apiflask/apiflask
repo_name: apiflask/apiflask
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/apiflask/apiflask
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/apiflask
copyright: Copyright &copy; 2021 <a href="https://greyli.com/en" target="_blank" rel="noopener">Grey Li</a>
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.progressbar
  - attr_list
  - toc:
        permalink: True
        slugify: !!python/name:pymdownx.slugs.uslugify
nav:
  - Home: index.md
  - Documentation Index: docs.md
  - Migrating from Flask: migrating.md
  - Basic Usage: usage.md
  - Request Handling: request.md
  - Response Formatting: response.md
  - Data Schema: schema.md
  - Authentication: authentication.md
  - OpenAPI Generating: openapi.md
  - Swagger UI and Redoc: api-docs.md
  - Configuration: configuration.md
  - Error Handling: error-handling.md
  - Examples: examples.md
  - API Reference:
    - APIFlask: api/app.md
    - APIBlueprint: api/blueprint.md
    - Exceptions: api/exceptions.md
    - OpenAPI: api/openapi.md
    - Schemas: api/schemas.md
    - Fields: api/fields.md
    - Validators: api/validators.md
    - Route: api/route.md
    - Security: api/security.md
    - Helpers: api/helpers.md
    - Commands: api/commands.md
  - Comparison and Motivations: comparison.md
  - Authors: authors.md
  - Changelog: changelog.md
  - Contributing Guide: contributing.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            heading_level: 2
      watch:
        - src/apiflask
        - README.md
        - examples/README.md
        - CHANGES.md
        - CONTRIBUTING.md
extra_css:
  - _assets/extra.css
