blank_issues_enabled: true
contact_links:
  - name: Security issue
    url: withlihui+security@gmail.com
    about: Do not report security issues publicly. Email our security contact.
  - name: Questions
    url: https://stackoverflow.com/questions/tagged/apiflask?tab=Frequent
    about: Search for or ask questions about your code on Stack Overflow.
  - name: Questions, discussions, and ideas (English)
    url: https://github.com/apiflask/apiflask/discussions
    about: Discuss questions, ideas about your code or APIFlask itself on our GitHub Discussion.
  - name: 问题 & 讨论（中文）
    url: https://discuss.helloflask.com/
    about: 欢迎在 HelloFlask 论坛创建关于 APIFlask 的问题和讨论（提问前请阅读置顶主题了解如何正确提问）。
